<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0">Content Pricing Editor</span>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Content Pricing</li>
            </ol>
        </nav>
    </div>
</nav>

<div class="container p-3">
    <div class="row">
        <div class="col-md-3">
            <div class="card mb-3">
                <form method="GET" class="card-body">
                    <h5 class="card-title">Search</h5>
                    <?php if($this->can_i->read_content_pricing_all): ?>
                        <?= $form->field('user', $filt_users) ?>
                    <?php endif; ?>
                    <?= $form->field('status') ?>
                    <?= $form->field('type', $types) ?>
                    <div id="filter-date">
                        <?= $form->field('month') ?>
                    </div>
                    <div class="text-right">
                        <button class="btn btn-primary">Find</button>
                    </div>
                </form>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                    <div>Total item: <?= number_format($total); ?></div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <?php if($pricings): ?>
                <?php $csrf = $form->csrfToken(); ?>
                <?php foreach($pricings as $pricing): ?>
                    <?php $creator = $pricing[0]->creator; ?>
                    <div class="card mb-3">
                        <div class="card-body">
                            <dl class="row">
                                <dt class="col-sm-2">Fullname</dt>
                                <dd class="col-sm-10"><?= $creator->fullname->safe ?></dd>
                                <?php if(isset($creator->email)): ?>
                                    <dt class="col-sm-2">Email</dt>
                                    <dd class="col-sm-10"><?= $creator->email->safe ?></dd>
                                <?php endif; ?>
                                <?php if(isset($creator->phone)): ?>
                                    <dt class="col-sm-2">Phone</dt>
                                    <dd class="col-sm-10"><?= $creator->phone->safe ?></dd>
                                <?php endif; ?>
                            </dl>

                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th class="text-right" style="width:60px;">No.</th>
                                        <th>Content</th>
                                        <th class="text-right" style="width:120px;">Price</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $price_total = 0; ?>
                                    <?php foreach($pricing as $index => $prc): ?>
                                        <?php $price_total+= $prc->price->value; ?>
                                        <tr>
                                            <td class="text-right"><?= ($index+1) ?>.</td>
                                            <td>
                                                <div><?= $prc->object->title->safe ?></div>
                                                <small>
                                                    <span title="Created"><?= $prc->object->created->format('M d, Y H:i') ?></span>
                                                    &middot;
                                                    <span title="Type"><?= $prc->type ?></span>
                                                    &middot;
                                                    <span title="Status"><?= $prc->object->status ?></span>
                                                </small>
                                            </td>
                                            <td class="text-right"><?= $prc->price->format() ?></td>
                                            <td class="text-right">
                                                <?php if($this->can_i->set_contennt_pricing): ?>
                                                    <?php
                                                        $data = [
                                                            'id'    => $prc->id,
                                                            'object'=> $prc->object->id,
                                                            'price' => $prc->price,
                                                            'month' => ( $prc->month ? $prc->month->format('Y-m') : date('Y-m') ),
                                                            'type'  => $prc->type
                                                        ];
                                                    ?>
                                                    <button data-object="<?= hs(json_encode($data)) ?>" class="btn btn-secondary btn-sm" type="button" title="Set Price" data-target="#pricing-set" data-toggle="modal">
                                                        <i class="fas fa-dollar-sign"></i>
                                                    </button>
                                                <?php endif; ?>
                                                <?php if($prc->id && $this->can_i->remove_content_pricing): ?>
                                                    <a
                                                        class="btn btn-secondary btn-sm"
                                                        title="Remove Price"
                                                        data-toggle="confirm"
                                                        data-text="Are you sure want to remove this item?"
                                                        data-btn-type="danger"
                                                        href="<?= $this->router->to('adminContentPricingRemove', ['id'=>$prc->id], ['noob'=>$csrf, 'reff'=>$this->req->url]) ?>">
                                                        <i class="fas fa-times"></i>
                                                    </a>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="2" class="text-right">
                                            Total
                                        </th>
                                        <th class="text-right">
                                            <?php 
                                                $price_total = new \LibFormatter\Object\Number($price_total);
                                                echo $price_total->format();
                                            ?>
                                        </th>
                                        <th></th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if($pages): ?>
                <?= $this->partial('shared/pagination', ['pages'=>$pages, 'align'=>'right']); ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<form method="POST" class="modal fade" tabindex="-1" role="dialog" id="pricing-set">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Set Content Pricing</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="hidden">
                    <?= $f_pricing->field('type') ?>
                    <?= $f_pricing->field('object') ?>
                    <?= $f_pricing->csrfField('noob') ?>
                    <input type="hidden" name="reff" value="<?= hs($this->req->url) ?>">
                </div>
                <?= $f_pricing->field('price') ?>
                <?= $f_pricing->field('month') ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function(){
        
        $('#admin-content-pricing-index-fld-status')
        .change(function(){
            $('#filter-date')[(this.value==1?'show':'hide')]()
        })
        .change();

        $('#pricing-set').on('show.bs.modal', function(e){
            var target = $(e.relatedTarget);
            var data   = target.data('object');
            $('#admin-content-pricing-edit-fld-month').val( data.month );
            $('#admin-content-pricing-edit-fld-price').val( data.price );
            $('#admin-content-pricing-edit-fld-object').val( data.object );
            $('#admin-content-pricing-edit-fld-type').val( data.type );

            var target = '<?= $this->router->to('adminContentPricingEdit', ['id'=>'-ID-']) ?>'.replace('-ID-', data.id);
            $('#pricing-set').attr('action', target);
            console.log(data);
        });
    }, false);
</script>
